//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Minutes_Master_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting_Minutes_Master_Tbl()
        {
            this.Meeting_Minutes_Details_Tbl = new HashSet<Meeting_Minutes_Details_Tbl>();
        }
    
        public int MeetingMinutesID { get; set; }
        public string CustomerType { get; set; }
        public Nullable<int> CorporateCustomerID { get; set; }
        public Nullable<int> IndividualCustomerID { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.TimeSpan MeetingTime { get; set; }
        public string MeetingPlace { get; set; }
        public string ClientAttendees { get; set; }
        public string HostAttendees { get; set; }
        public string Agenda { get; set; }
        public string Discussion { get; set; }
        public string Decision { get; set; }
    
        public virtual Corporate_Customer_Tbl Corporate_Customer_Tbl { get; set; }
        public virtual Individual_Customer_Tbl Individual_Customer_Tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Minutes_Details_Tbl> Meeting_Minutes_Details_Tbl { get; set; }
    }
}
