//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPM.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Service_Tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products_Service_Tbl()
        {
            this.Meeting_Minutes_Details_Tbl = new HashSet<Meeting_Minutes_Details_Tbl>();
        }
    
        public int ProductServiceID { get; set; }
        public string ProductServiceName { get; set; }
        public string Unit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting_Minutes_Details_Tbl> Meeting_Minutes_Details_Tbl { get; set; }
    }
}
