//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPMT.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting_Minutes_Details_Tbl
    {
        public int DetailID { get; set; }
        public int MeetingID { get; set; }
        public int ProductServiceID { get; set; }
        public int Quantity { get; set; }
        public string Unit { get; set; }
    
        public virtual Meeting_Minutes_Master_Tbl Meeting_Minutes_Master_Tbl { get; set; }
        public virtual Products_Service_Tbl Products_Service_Tbl { get; set; }
    }
}
