//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactManagement.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int NoteId { get; set; }
        public int ContactId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
