//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int id { get; set; }
        public string name { get; set; }
        public string cgpa { get; set; }
        public string fathername { get; set; }
        public string mothername { get; set; }
        public string religion { get; set; }
        public string gender { get; set; }
        public string studentinterest { get; set; }
        public System.DateTime dateofbirth { get; set; }
        public Nullable<int> deptId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
